module.exports = {
    inserir: require('./inserir'),
    listar: require('./listar'),
    alterar: require('./alterar'),
    alterarFoto: require('./alterarFoto'),
    deletar: require('./deletar'),
    pesquisaAvancada: require('./pesquisaAvancada'),
    pesquisa: require('./pesquisaSimples'),
    getGeneros: require('./getGeneros'),
    getDestaques: require('./getDestaques'),
    uploadPrints: require('./uploadPrints'),
    getEpisodio: require('./getEpisodio'),
    listarTodos: require('./listarTodos'),
    getMaisAcessados: require('./getMaisAcessados'),
    getTopAnimes: require('./getTopAnimes'),
    getUltimosAnimes: require('./getUltimosAnimes'),
    getAnimesInfo: require('./getAnimesInfo'),
    getFuturosLancamentos: require('./getFuturosLancamentos'),
    alterarPrints: require('./alterarPrints')
}